// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3dwqiJ9Nd5A5u07iwVK_fgR9ydgkd0M',
    appId: '1:766685133984:web:e2b01e738e08a03e8d9dc5',
    messagingSenderId: '766685133984',
    projectId: 'afro-ce148',
    authDomain: 'afro-ce148.firebaseapp.com',
    storageBucket: 'afro-ce148.firebasestorage.app',
    measurementId: 'G-JJBRQ14E9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7CLS6_HnDvGfVp6vEHnYX4xaaji27B4',
    appId: '1:766685133984:android:50148116d2a1f9308d9dc5',
    messagingSenderId: '766685133984',
    projectId: 'afro-ce148',
    storageBucket: 'afro-ce148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdfc9RybEiiSNugmpx46ENTCyqmTugA2Y',
    appId: '1:766685133984:ios:ddbbbfc74af39c518d9dc5',
    messagingSenderId: '766685133984',
    projectId: 'afro-ce148',
    storageBucket: 'afro-ce148.firebasestorage.app',
    androidClientId: '766685133984-d6j33i9ce881v5c192o20la912gtb55p.apps.googleusercontent.com',
    iosClientId: '766685133984-2ari3vqr766pc97n1sn41gq7lf09tunu.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdfc9RybEiiSNugmpx46ENTCyqmTugA2Y',
    appId: '1:766685133984:ios:ddbbbfc74af39c518d9dc5',
    messagingSenderId: '766685133984',
    projectId: 'afro-ce148',
    storageBucket: 'afro-ce148.firebasestorage.app',
    androidClientId: '766685133984-d6j33i9ce881v5c192o20la912gtb55p.apps.googleusercontent.com',
    iosClientId: '766685133984-2ari3vqr766pc97n1sn41gq7lf09tunu.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu3dwqiJ9Nd5A5u07iwVK_fgR9ydgkd0M',
    appId: '1:766685133984:web:b11db62fd0a2db878d9dc5',
    messagingSenderId: '766685133984',
    projectId: 'afro-ce148',
    authDomain: 'afro-ce148.firebaseapp.com',
    storageBucket: 'afro-ce148.firebasestorage.app',
    measurementId: 'G-RV9ZQCLXQH',
  );

}